twisted.python.failure.Failure now raises the wrapped exception in Python3, and self (Failure) when trap() is called without a matching exception
